name: Push to Another Repository with a Signed Commit
description: >-
  Push files to another repository. Ideal for GitHub Pages, docs sync, and
  mirrors. Creates signed commits with App tokens.
inputs:
  token:
    description: Github token with write access to the destination repository
    required: false
    default: ${{ github.token }}
  destination-repository:
    description: Destination repository
    required: true
  source-directory:
    description: '[Optional] Source directory from the origin directory'
    default: '.'
    required: false
  destination-branch:
    description: >-
      [Optional] set destination branch name for the destination repository. Defaults
      to "main"
    default: main
    required: false
  commit-message:
    description: >-
      [Optional] commit message for the output repository.
      LAST_COMMIT_MESSAGE is replaced by the last commit message in the source repo
      ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
      GIT_REF is replaced by the origin $GIT_REF
    default: 'LAST_COMMIT_MESSAGE (via ORIGIN_COMMIT from GITHUB_REF)'
    required: false
  destination-directory:
    description: '[Optional] The directory to wipe and replace in the destination repository'
    default: ''
    required: false
outputs:
  pushed:
    description: 'Whether a commit was pushed to the destination repository'
    value: ${{ steps.commit.outputs.pushed }}
runs:
  using: composite
  steps:
  - name: Checkout destination repository into a worktree
    uses: actions/checkout@v4
    with:
      repository: ${{ inputs.destination-repository }}
      token: ${{ inputs.token }}
      ref: ${{ inputs.destination-branch }}
      persist-credentials: false
      path: .push-to-another-repository
  - id: prepare
    name: "Prepare the destination repository in the workspace before committing"
    run: $GITHUB_ACTION_PATH/entrypoint.sh
    shell: bash
    env:
      SOURCE_DIRECTORY: ${{ inputs.source-directory }}
      COMMIT_MESSAGE: ${{ inputs.commit-message }}
      DESTINATION_DIRECTORY: ${{ inputs.destination-directory }}
      WORKTREE_DIR: .push-to-another-repository
  - id: commit
    uses: suzuki-shunsuke/commit-action@v0.0.10
    with:
      github_token: ${{ inputs.token }}
      repository: ${{ inputs.destination-repository }}
      commit_message: ${{ steps.prepare.outputs.commit-message }}
      branch: ${{ inputs.destination-branch }}
  - name: restore stashed original workspace from worktree
    run: |
      TEMP_DIR="$(mktemp -d)/$WORKTREE_DIR"
      mv ./$WORKTREE_DIR "$TEMP_DIR"
      rm -rf "$GITHUB_WORKSPACE"
      mv "$TEMP_DIR" "$GITHUB_WORKSPACE"
    shell: bash
    env:
      WORKTREE_DIR: .push-to-another-repository
branding:
  icon: git-commit
  color: green
