name: Songmu/action-push-to-another-repository
description: >-
  Push files to another repository. Ideal for GitHub Pages, docs sync, and
  mirrors. Creates signed commits with App tokens.
inputs:
  github-token:
    description: Github token with write access to the destination repository
    required: true
  destination-repository:
    description: Destination repository
    required: true
  source-directory:
    description: '[Optional] Source directory from the origin directory'
    default: '.'
    required: false
  destination-branch:
    description: >-
      [Optional] set destination branch name for the destination repository. Defaults
      to "main"
    default: main
    required: false
  commit-message:
    description: >-
      [Optional] commit message for the output repository.
      LAST_COMMIT_MESSAGE is replaced by the last commit message in the source repo
      ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
      GIT_REF is replaced by the origin $GIT_REF
    default: 'LAST_COMMIT_MESSAGE (via ORIGIN_COMMIT from GITHUB_REF)'
    required: false
  destination-directory:
    description: '[Optional] The directory to wipe and replace in the destination repository'
    default: ''
    required: false
runs:
  using: composite
  steps:
  - name: Checkout source repository
    uses: actions/checkout@v4
    with:
      repository: ${{ inputs.destination-repository }}
      token: ${{ inputs.github-token }}
      ref: ${{ inputs.destination-branch }}
      path: .push-to-another-repository
  - id: prepare
    run: $GITHUB_ACTION_PATH/entrypoint.sh
    shell: bash
    env:
      SOURCE_DIRECTORY: ${{ inputs.source-directory }}
      COMMIT_MESSAGE: ${{ inputs.commit-message }}
      DESTINATION_DIRECTORY: ${{ inputs.destination-directory }}
      WORKTREE_DIR: .push-to-another-repository
  - uses: suzuki-shunsuke/commit-action@v0.0.8
    with:
      github_token: ${{ inputs.github-token }}
      repository: ${{ inputs.destination-repository }}
      commit_message: ${{ steps.prepare.outputs.commit-message }}
      branch: ${{ inputs.destination-branch }}
  - name: restore origin
    run: |
      WORKTREE_DIR=".push-to-another-repository"
      TEMP_DIR="$(mktemp -d)/$WORKTREE_DIR"
      mv ./$WORKTREE_DIR "$TEMP_DIR"
      rm -rf "$GITHUB_WORKSPACE"
      mv "$TEMP_DIR" $GITHUB_WORKSPACE
    shell: bash
branding:
  icon: git-commit
  color: green
