name: Push directory to another repository
description: >-
  Useful to push files to another repository to be used, for example, via github
  pages
inputs:
  github-token:
    description: Github token with write access to the destination repository
    required: true
  source-directory:
    description: Source directory from the origin directory
    required: true
  destination-repository:
    description: Destination repository
    required: true
  github-server:
    description: 'Github server'
    default: 'github.com'
    required: false
  target-branch:
    description: >-
      [Optional] set target branch name for the destination repository. Defaults
      to "main"
    default: main
    required: false
  commit-message:
    description: >-
      [Optional] commit message for the output repository.
      LAST_COMMIT_MESSAGE is replaced by the last commit message in the source repo
      ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
    default: 'LAST_COMMIT_MESSAGE (via ORIGIN_COMMIT from GITHUB_REF)'
    required: false
  target-directory:
    description: '[Optional] The directory to wipe and replace in the target repository'
    default: ''
    required: false
  create-target-branch-if-needed:
    description: >-
      [Optional] create target branch if not exist. Defaults to `false`
    default: "false"
    required: false
runs:
  using: composite
  steps:
  - id: prepare
    run: $GITHUB_ACTION_PATH/entrypoint.sh
    shell: bash
    env:
      API_TOKEN_GITHUB: ${{ inputs.github-token }}
      SOURCE_DIRECTORY: ${{ inputs.source-directory }}
      DESTINATION_REPOSITORY: ${{ inputs.destination-repository }}
      GITHUB_SERVER: ${{ inputs.github-server }}
      TARGET_BRANCH: ${{ inputs.target-branch }}
      COMMIT_MESSAGE: ${{ inputs.commit-message }}
      TARGET_DIRECTORY: ${{ inputs.target-directory }}
      CREATE_TARGET_BRANCH_IF_NEEDED: ${{ inputs.create-target-branch-if-needed }}
  - uses: suzuki-shunsuke/commit-action@v0.0.8
    with:
      github_token: ${{ inputs.github-token }}
      repository: ${{ inputs.destination-repository }}
      commit_message: ${{ steps.prepare.outputs.commit-message }}
      branch: ${{ inputs.target-branch }}
branding:
  icon: git-commit
  color: green
