name: release
description: release action-push-to-another-repository
inputs:
  tag:
    description: tag name to be released
    default: ''
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
  - uses: haya14busa/action-update-semver@v1
    with:
      github_token: ${{ inputs.token }}
      tag: ${{ inputs.tag }}
      major_version_tag_only: true
